---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "ImageStream"
  metadata:
    name: "twitter"
  spec:
    tags:
    - from:
        kind: "ImageStreamImage"
        name: "twitter@sha256:46d54838f3d7fbbd80ede1d9b39200b2bb4f70be18e50ac9f8842b5a632349b1"
        namespace: "game-apps-dev"
      name: "latest"
