---
apiVersion: "v1"
kind: "Service"
metadata:
  annotations:
    fabric8.io/git-commit: "611fdf7e2c80054bf9ce3bda87583a5355d17ba0"
    fabric8.io/iconUrl: "img/icons/camel.svg"
    fabric8.io/git-branch: "master"
  labels:
    expose: "true"
    provider: "fabric8"
    project: "twitter"
    version: "1.0-SNAPSHOT"
    group: "com.rettori"
  name: "twitter"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    project: "twitter"
    provider: "fabric8"
    group: "com.rettori"
